# This file controls the settings for the web site

# website settings
website:
  title: "Mako Bračić"                                # Your name
  description: "Behavioural biologist"   # A brief slogan (optional)
  image: img/MarkoBracic.jpg
  favicon: img/ant.png

  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/ant.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      # - text: "Talks"
      #   href: talks/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - text: ORCiD
        href: https://orcid.org/0000-0001-6528-3572
      - icon: linkedin
        href: http://www.linkedin.com/in/markobračić
      - icon: twitter
        href: https://twitter.com/MarkoBracic
      - icon: envelope
        aria-label: email
        href: "mailto:mbracic192@gmail.com"
        
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Marko Bracic CC0 1.0 License</span>
    # right: |
    #   <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    email-obfuscation: javascript