# This file controls the settings for the web site
authorname: "Marko Bračić"
draft: false

# website settings
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

title-meta: "Marko Bračić, behavioural biologist"
description-meta: "Behavioural ecology | Animal personality| Optimism | Ants,| Data analyisis | Research | Cognition"


website:
  title: "Marko Bračić"
  description: "Behavioural ecology | Animal personality| Optimism | Ants,| Data analyisis | Research | Cognition"
  image: img/MarkoBracic.jpg
  favicon: img/ant.png

  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/ant.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      # - text: "Talks"
      #   href: talks/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - text: ORCiD
        href: https://orcid.org/0000-0001-6528-3572
      - icon: linkedin
        href: http://www.linkedin.com/in/markobračić
      - icon: twitter
        href: https://twitter.com/MarkoBracic
      - icon: envelope
        aria-label: email
        href: "mailto:mbracic192@gmail.com"
        
  
  

  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: © 2024 Marko Bračić
    right: |
       <span class="faux-block">
       View source code on <a href="https://github.com/markobracic/markobracic.github.io"> my GitHub</a> 
       </span>
       <span class="faux-block"> 
       Built with R and <a href="https://quarto.org/">Quarto</a></span>
       
  twitter-card: 
    creator: "@MarkoBracic"
    title: "Dr. Marko Bračić<br> <small style='font-size: 50%;'>Behavioural biologist</small>"
    image: img/MarkoBracic.jpg
    card-style: summary_large_image
    
  open-graph:
    title: "Dr. Marko Bračić<br> <small style='font-size: 50%;'>Behavioural biologist</small>"
    image: img/MarkoBracic.jpg
    locale: en_US

       

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    email-obfuscation: javascript